@Host = localhost
@Port = 8080

GET http://{{Host}}:{{Port}}/api/users

###

GET http://{{Host}}:{{Port}}/api/users/e3097561-2c66-4b61-8c33-cee65a83005y

###

POST http://{{Host}}:{{Port}}/api/users
Content-type: application/json

{}

###

PUT http://{{Host}}:{{Port}}/api/users/1
Content-type: application/json

{}

###

DELETE http://{{Host}}:{{Port}}/api/users/1
Content-type: application/json

{}

###

