@Host = localhost
@Port = 8080

GET http://{{Host}}:{{Port}}/api/users

###

GET http://{{Host}}:{{Port}}/api/users/e89dbee7-555c-494a-a8c0-a452827d4543

###

POST http://{{Host}}:{{Port}}/api/users
Content-type: application/json

{
    "first_name": "Jason",
	"last_name": "Ivanov",
	"email": "j.ivanov@mail.ru",
	"phone": "+334239999999",
	"login": "jason_ivanov_45",
	"password": "qwerty12345",
	"repeat_password": "qwerty12345"
}

###

PUT http://{{Host}}:{{Port}}/api/users/e89dbee7-555c-494a-a8c0-a452827d4543
Content-type: application/json

{
    "first_name": "Johny",
	"last_name": "Petrov",
	"email": "petrov.jo@mail.ru",
	"phone": "+334239999988",
	"login": "johny_petrov_99",
	"old_password": "qwerty12345",
	"new_password": "qwerty56789"
}

###

DELETE http://{{Host}}:{{Port}}/api/users/e89dbee7-555c-494a-a8c0-a452827d4543
Content-type: application/json

{}

###

